# allowed_ips_application = ["0.0.0.0/0"]
# availability_zone = "us-east-1a"
# instance_type = "t3.2xlarge"
login_email = "login.email@example.com"
# region = "us-east-1"
# root_volume_size = 32
# storage_bucket = "opencti-storage"
subnet_id = ""
vpc_id = ""
